"""Se agrego el atributo slug en el modelo de usuario

Revision ID: c745cbea483a
Revises: a55cca6f2576
Create Date: 2025-09-24 15:33:52.647451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c745cbea483a'
down_revision: Union[str, Sequence[str], None] = 'a55cca6f2576'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('slug', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_users_slug'), 'users', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_slug'), table_name='users')
    op.drop_column('users', 'slug')
    # ### end Alembic commands ###
